import React, { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import API from "../services/api";
import { useTheme } from "../ThemeContext";
import "./Reports.css";

function Reports() {
  const [attendance, setAttendance] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const { theme, toggleTheme } = useTheme();
  const navigate = useNavigate();

  useEffect(() => {
    fetchAttendance();
  }, []);

  const fetchAttendance = async () => {
    try {
      setLoading(true);
      setError("");

      const response = await API.get("/attendance");
      setAttendance(response.data);
    } catch (error) {
      console.log("Error fetching attendance:", error);
      setError("Unable to load attendance records.");
    } finally {
      setLoading(false);
    }
  };

  const handleLogout = () => {
    sessionStorage.removeItem("loggedInUser");
    navigate("/login");
  };

  // Calculate attendance percentage
  const getPercentage = (record) => {
    if (!record.totalClasses || record.totalClasses === 0) {
      return 0;
    }

    return Math.round(
      (Number(record.present) / Number(record.totalClasses)) * 100
    );
  };

  // Generate PDF
  const generatePDF = () => {
    if (attendance.length === 0) {
      alert("No attendance records available to generate the report.");
      return;
    }

    const doc = new jsPDF();

    // Title
    doc.setFontSize(20);
    doc.text("Attendify", 14, 20);

    doc.setFontSize(16);
    doc.text("Attendance Report", 14, 30);

    // Report information
    doc.setFontSize(10);
    doc.text(
      `Generated on: ${new Date().toLocaleDateString("en-IN")}`,
      14,
      40
    );

    doc.text(
      `Total Records: ${attendance.length}`,
      14,
      47
    );

    // Table data
    const tableData = attendance.map((record) => [
      record.studentName,
      record.studentId,
      record.course,
      record.date,
      record.status,
      record.totalClasses,
      record.present,
      record.absent,
      `${getPercentage(record)}%`,
    ]);

    autoTable(doc, {
      startY: 55,

      head: [[
        "Student",
        "ID",
        "Course",
        "Date",
        "Status",
        "Total",
        "Present",
        "Absent",
        "Percentage",
      ]],

      body: tableData,

      theme: "grid",

      styles: {
        fontSize: 7,
        cellPadding: 2,
      },

      headStyles: {
        fontSize: 7,
        fontStyle: "bold",
      },

      alternateRowStyles: {
        fillColor: [245, 247, 250],
      },
    });

    // Footer
    const finalY = doc.lastAutoTable.finalY || 55;

    doc.setFontSize(9);
    doc.text(
      "Generated by Attendify - Student Attendance Manager",
      14,
      finalY + 15
    );

    doc.save("Attendify-Attendance-Report.pdf");
  };

  // Calculate summary
  const totalRecords = attendance.length;

  const presentRecords = attendance.filter(
    (record) => record.status === "Present"
  ).length;

  const absentRecords = attendance.filter(
    (record) => record.status === "Absent"
  ).length;

  const averageAttendance =
    attendance.length > 0
      ? Math.round(
          attendance.reduce(
            (total, record) => total + getPercentage(record),
            0
          ) / attendance.length
        )
      : 0;

  return (
    <div className="reports-layout">

      {/* Sidebar */}
      <aside className="reports-sidebar">

        <div className="reports-sidebar-logo">
          <h2>
            Attend<span>ify</span>
          </h2>
        </div>

        <nav className="reports-sidebar-menu">
          <Link to="/dashboard">
            Dashboard
          </Link>

          <Link to="/attendance">
            Attendance
          </Link>

          <Link to="/calendar">
            Calendar
          </Link>

          <Link
            to="/reports"
            className="active"
          >
            Reports
          </Link>
        </nav>

        <div className="reports-sidebar-bottom">

          <button
            className="reports-theme-toggle"
            onClick={toggleTheme}
          >
            {theme === "dark"
              ? "☀️ Light Mode"
              : "🌙 Dark Mode"}
          </button>

          <button
            className="reports-logout-btn"
            onClick={handleLogout}
          >
            Logout
          </button>

        </div>

      </aside>

      {/* Main Content */}
      <main className="reports-main">

        <div className="reports-header">

          <div>
            <h1>Attendance Reports</h1>
            <p>
              View attendance summary and generate detailed reports
            </p>
          </div>

          <button
            className="download-report-btn"
            onClick={generatePDF}
          >
            📄 Download PDF
          </button>

        </div>

        {/* Error */}
        {error && (
          <div className="reports-error">
            {error}

            <button onClick={fetchAttendance}>
              Try Again
            </button>
          </div>
        )}

        {/* Loading */}
        {loading ? (
          <div className="reports-loading">
            <div className="reports-spinner"></div>
            <p>Loading attendance records...</p>
          </div>
        ) : (
          <>
            {/* Summary Cards */}
            <div className="report-summary">

              <div className="report-card">
                <span className="report-card-icon">
                  📋
                </span>

                <div>
                  <p>Total Records</p>
                  <h2>{totalRecords}</h2>
                </div>
              </div>

              <div className="report-card">
                <span className="report-card-icon">
                  ✓
                </span>

                <div>
                  <p>Present</p>
                  <h2>{presentRecords}</h2>
                </div>
              </div>

              <div className="report-card">
                <span className="report-card-icon">
                  ✕
                </span>

                <div>
                  <p>Absent</p>
                  <h2>{absentRecords}</h2>
                </div>
              </div>

              <div className="report-card">
                <span className="report-card-icon">
                  📊
                </span>

                <div>
                  <p>Average Attendance</p>
                  <h2>{averageAttendance}%</h2>
                </div>
              </div>

            </div>

            {/* Report Table */}
            <div className="report-table-container">

              <div className="report-table-header">
                <div>
                  <h2>Attendance Details</h2>
                  <p>
                    Complete attendance records
                  </p>
                </div>

                <button
                  className="refresh-report-btn"
                  onClick={fetchAttendance}
                >
                  ↻ Refresh
                </button>
              </div>

              {attendance.length > 0 ? (
                <div className="report-table-wrapper">

                  <table className="report-table">

                    <thead>
                      <tr>
                        <th>Student</th>
                        <th>ID</th>
                        <th>Course</th>
                        <th>Date</th>
                        <th>Status</th>
                        <th>Total</th>
                        <th>Present</th>
                        <th>Absent</th>
                        <th>Percentage</th>
                      </tr>
                    </thead>

                    <tbody>

                      {attendance.map((record) => {

                        const percentage =
                          getPercentage(record);

                        return (
                          <tr key={record.id}>

                            <td>
                              <strong>
                                {record.studentName}
                              </strong>
                            </td>

                            <td>
                              {record.studentId}
                            </td>

                            <td>
                              {record.course}
                            </td>

                            <td>
                              {record.date}
                            </td>

                            <td>
                              <span
                                className={
                                  record.status === "Present"
                                    ? "report-status present"
                                    : "report-status absent"
                                }
                              >
                                {record.status}
                              </span>
                            </td>

                            <td>
                              {record.totalClasses}
                            </td>

                            <td>
                              {record.present}
                            </td>

                            <td>
                              {record.absent}
                            </td>

                            <td>
                              <span className="percentage-value">
                                {percentage}%
                              </span>
                            </td>

                          </tr>
                        );
                      })}

                    </tbody>

                  </table>

                </div>
              ) : (
                <div className="reports-empty">
                  <div>📊</div>
                  <h3>No Attendance Records</h3>
                  <p>
                    Add attendance records to generate a report.
                  </p>

                  <Link to="/attendance">
                    Go to Attendance
                  </Link>
                </div>
              )}

            </div>
          </>
        )}

      </main>

    </div>
  );
}

export default Reports;